/*
brand_health
*/
ALTER TABLE brand_health ALTER COLUMN ID INT NOT NULL
ALTER TABLE brand_health ALTER COLUMN Year VARCHAR(255) NOT NULL
ALTER TABLE brand_health ALTER COLUMN Brand VARCHAR(255) NOT NULL
ALTER TABLE brand_health ALTER COLUMN Spontaneous BIT NULL
ALTER TABLE brand_health ALTER COLUMN Awareness BIT NULL
ALTER TABLE brand_health ALTER COLUMN Trial BIT NULL
ALTER TABLE brand_health ALTER COLUMN P1M BIT NULL
ALTER TABLE brand_health ALTER COLUMN P3M BIT NULL

ALTER TABLE brand_health
ADD PRIMARY KEY (ID, Brand)


/*
brand_image
*/
ALTER TABLE brand_image ALTER COLUMN ID INT NOT NULL
ALTER TABLE brand_image ALTER COLUMN Year VARCHAR(255) NOT NULL
ALTER TABLE brand_image ALTER COLUMN Awareness VARCHAR(255) NOT NULL


/*
sa_var
*/
ALTER TABLE sa_var ALTER COLUMN ID INT NOT NULL

ALTER TABLE sa_var
ADD PRIMARY KEY (ID)


/*
segmentation
*/
ALTER TABLE segmentation ALTER COLUMN ID INT NOT NULL
ALTER TABLE segmentation ALTER COLUMN Brand VARCHAR(255) NOT NULL

ALTER TABLE segmentation
ADD PRIMARY KEY (ID, Brand)


/* 
competitor
*/
ALTER TABLE competitor ALTER COLUMN Year VARCHAR(255) NOT NULL
ALTER TABLE competitor ALTER COLUMN Brand VARCHAR(255) NOT NULL
ALTER TABLE competitor ALTER COLUMN City VARCHAR(255) NOT NULL


ALTER TABLE competitor
ADD PRIMARY KEY (Brand, City, Year)

/*
Dayofweek
*/
ALTER TABLE day_of_week ALTER COLUMN ID INT NOT NULL
ALTER TABLE day_of_week ALTER COLUMN Year INT NOT NULL
ALTER TABLE day_of_week ALTER COLUMN Dayofweek VARCHAR(255) NOT NULL
ALTER TABLE day_of_week ALTER COLUMN Weekday#end VARCHAR(255) NOT NULL
ALTER TABLE day_of_week ALTER COLUMN City VARCHAR(255) NOT NULL


/*
day_part
*/
ALTER TABLE day_part ALTER COLUMN ID INT NOT NULL
ALTER TABLE day_part ALTER COLUMN Daypart VARCHAR(255) NOT NULL
ALTER TABLE day_part ALTER COLUMN City VARCHAR(255) NOT NULL
ALTER TABLE day_part ALTER COLUMN Visit#Daypart INT NOT NULL

ALTER TABLE day_part
ADD PRIMARY KEY (ID, Daypart)


